name: van_app_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Dependências de Rede e Utils
  http: ^1.2.1
  shared_preferences: ^2.2.3
  jwt_decoder: ^2.0.1
  web_socket_channel: ^2.4.5
  geolocator: ^10.1.0  # Para pegar o GPS real
  action_slider: ^0.7.0 # Para o botão de confirmar embarque estilo Uber
  flutter_compass: ^0.8.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9 # Para notificações


  # --- CORREÇÃO AQUI: Trocamos Google Maps por Flutter Map ---
  flutter_map: ^6.0.0       # Necessário para o MapScreen
  latlong2: ^0.9.0          # Necessário para coordenadas (LatLng)
  # google_maps_flutter: ^2.6.1  <-- Removido para evitar conflitos

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true